licencias/licencias/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^licenciatarios/', include('licenciatarios.urls'))

]

licencias/licenciatarios/urls.py
from django.conf.urls import url
from .views import  *
from django.contrib.auth import views as auth_views

from . import views

app_name = 'licenciatarios'
urlpatterns = [
    # url(r'^(?P<id>\d+)/$', views.licencia_edit, name='licencia-edit'),
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.licencia_nueva, name='licencia-nueva'),
    url(r'^print/(?P<id>\d+)/$', views.show_licencia, name='print-licencia'),
    # url(r'^print/(?P<userid>\d+)$', views.print_licencia, name='print_licencia'),
    url(r'^add/$', LicenciaCreate.as_view(), name='licencia-add'),
    url(r'^(?P<pk>[0-9]+)/$', LicenciaUpdate.as_view(), name ='licencia-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', LicenciaDelete.as_view(), name='licencia-delete'),
    url(r'^config/$', ConfigUpdate.as_view(), name='config'),

    url(r'^usr/$', UsuarioList.as_view(), name='usuario'),
    url(r'^usr/add/$', UsuarioCreate.as_view(), name='usuario-add'),
    url(r'^usr/(?P<pk>[0-9]+)/$', UsuarioUpdate.as_view(), name ='usuario-update'),
    url(r'^usr/(?P<pk>[0-9]+)/delete/$', UsuarioDelete.as_view(), name='usuario-delete'),

    url(r'^login/$', auth_views.login, name='login-view'),
    url(r'^logout/$', auth_views.logout, name='logout-view'),

]


# url(r'^User/(?P<userid>\d+)/$', 'search.views.user_detail', name='user_details'),

licencias/licenciatarios/models.py
from django.db import models
from django.contrib import admin
from django.utils.html import format_html
from django.urls import reverse
from django.contrib.auth.models import User

class configuraciones(models.Model):
    firma_autoridad = models.CharField(max_length=200)
    periodo_valido = models.CharField(max_length=200)

# Create your models here.
class Licenciatarios(models.Model):
    folio = models.CharField(max_length=200)
    nombre = models.CharField(max_length=200)
    razon_social = models.CharField(max_length=200)
    nombre_comercial = models.CharField(max_length=200)
    domicilio = models.CharField(max_length=200)
    colonia = models.CharField(max_length=200)
    municipio = models.CharField(max_length=200)
    entidad = models.CharField(max_length=200)
    cp = models.IntegerField()
    latlng = models.CharField(max_length=200, blank=True)
    telefono = models.IntegerField()
    correo = models.EmailField()
    rfc = models.CharField(max_length=200)
    actividad = models.CharField(max_length=200)
    horario = models.CharField(max_length=200)
    expedicion_fecha = models.DateField()
    vencimiento_fecha = models.DateField()
    # user = models.ForeignKey(User, related_name='created_by')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('licenciatarios:index')
        # return reverse('licencia-detail', kwargs={'pk': self.pk})


    def __str__(self):
        space = ' '
        return self.nombre_comercial+space+'('+self.nombre+')'

licencias/licenciatarios/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, HiddenInput
from django.contrib.auth.models import User
from .models import Licenciatarios

next_id = '10100'
try:
    if Licenciatarios.objects.latest('folio').exists():
        current_id = Licenciatarios.objects.latest('folio')
        next_id = int(current_id.folio) + 1
except:
    print('sadfa')



def add_css_classes(f, **kwargs):
    field - f.formfield(**kwargs)
    if field and 'class' not in field.widget.attrs:
        field.widget.attrs['class'] = 'form-control'
    return field



class AddLicenciatario(ModelForm):
    formafield_callback = add_css_classes
    """docstring for AddLicenciatario."""
    class Meta:
        model = Licenciatarios
        exclude = []
        labels = {
            'folio':'FOLIO'
        }
        help_texts = {
            'folio':'El folio debe ser de seis digitos'
        }
        widgets = {
            'folio': TextInput(attrs={
                'class':'form-control',
                'placeholder':'0001',
                'value' : next_id,
                'autofocus':''
            }),
            'actividad':Textarea(attrs={
                'class':'form-control',
            }),
            'horario': Textarea(attrs={
                'class':'form-control',
            }),
            'nombre': TextInput(attrs={
                'class':'form-control',
            }),
            'razon_social': TextInput(attrs={
                'class':'form-control',
            }),
            'nombre_comercial': TextInput(attrs={
                'class':'form-control',
            }),
            'domicilio': TextInput(attrs={
                'class':'form-control',
            }),
            'colonia': TextInput(attrs={
                'class':'form-control',
            }),
            'municipio': TextInput(attrs={
                'class':'form-control',
            }),
            'entidad': TextInput(attrs={
                'class':'form-control',
            }),
            'cp': TextInput(attrs={
                'class':'form-control',
            }),
            'telefono': TextInput(attrs={
                'class':'form-control',
            }),
            'correo': TextInput(attrs={
                'class':'form-control',
            }),
            'rfc': TextInput(attrs={
                'class':'form-control',
            }),
            'expedicion_fecha': TextInput(attrs={
                'class':'form-control',
            }),
            'vencimiento_fecha': TextInput(attrs={
                'class':'form-control',
            }),
            'latlng': HiddenInput()
        }
        #
    # nombre = forms.CharField(label='Nombre del licenciatario', max_length=200)
    # # apellido = forms.CharField(label='Apellido', max_length=300)

licencias/licenciatarios/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from .models import Licenciatarios
from django.contrib.auth.models import User
from datetime import date
#//////////////////////////

from .forms import AddLicenciatario

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, View
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def index(request):
    latest_licenciatarios = list(Licenciatarios.objects.order_by('-id'))

    for lic in latest_licenciatarios:
        # print(date.date(lic.expedicion_fecha))
        lic.status = lic.expedicion_fecha - date.today()


    ctx = {
        'licenciatarios':latest_licenciatarios,
    }
    return render(request, 'licenciatarios/index.html', ctx)

@login_required
def show_licencia(request, id):
    return print_licencia(id)

@login_required
def print_licencia(id):

    l = Licenciatarios.objects.get(pk=id)

    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="%s.pdf"' % l.folio

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.setFont("Helvetica", 30)
    p.drawString(250, 705, l.folio)
    p.setFont("Helvetica", 11)
    p.drawString(100, 678, l.nombre)
    p.drawString(95, 661, l.razon_social)
    p.drawString(165, 647, l.nombre_comercial)
    p.drawString(210, 630, l.domicilio+ ', '+l.colonia+', '+l.municipio+', '+l.entidad)
    p.drawString(460, 595, str(l.cp))

    p.drawString(25, 580, str(l.telefono))
    p.drawString(260, 580, l.correo)
    p.drawString(465, 580, l.rfc)

    p.drawString(0, 520, l.actividad)
    p.drawString(0, 445, l.horario)


    p.drawString(250, 245, str(l.expedicion_fecha))
    p.drawString(250, 205, str(l.vencimiento_fecha))


    # Close the PDF object cleanly, and we're done.
    p.showPage()

    p.save()

    return response
@login_required
def licencia_nueva(request):
    next_id = '10100'
    try:
        if Licenciatarios.objects.latest('folio').exists():
            current_id = Licenciatarios.objects.latest('folio')
            next_id = int(current_id.folio) + 1
    except:
        print('No existia la licencia')
    ctx = {}
    if request.method == 'POST':
        form =  AddLicenciatario(request.POST)
        if form.is_valid():
            formResult = form.save()
            pdf = print_licencia(current_id.pk)
            return pdf
        else:
            return render(request, 'licenciatarios/add-licenciatario.html', {'form':form})
    else:
        ctx['form'] = AddLicenciatario()
        ctx['title'] = 'Agrega un licenciatario'
        return render(request, 'licenciatarios/add-licenciatario.html', ctx)

@login_required
def licencia_edit(request, id):
    licenciatario = Licenciatarios.objects.get(pk=id)
    ctx = {}
    ctx['form'] = AddLicenciatario()
    ctx['title'] = 'Editar un licenciatario'
    return render(request, 'licenciatarios/add-licenciatario.html', ctx)


class LicenciaCreate(LoginRequiredMixin, CreateView):
    model = Licenciatarios
    form_class = AddLicenciatario
    template_name='licenciatarios/add-licenciatario.html'
    success_url = reverse_lazy('licenciatarios:index')

class LicenciaUpdate(LoginRequiredMixin, UpdateView):

    model = Licenciatarios
    form_class = AddLicenciatario
    success_url = reverse_lazy('licenciatarios:index')
class LicenciaDelete(LoginRequiredMixin, DeleteView):
    model = Licenciatarios
    success_url = reverse_lazy('licenciatarios:index')


class UsuarioList(LoginRequiredMixin, ListView):
    model = User

class UsuarioCreate(LoginRequiredMixin, CreateView):
    model = User
    fields = ['username', 'email', 'password']
    success_url = reverse_lazy('licenciatarios:usuario')

    def form_valid(self, form):
        user = User.objects.create_user(form.cleaned_data['username'],
                                        form.cleaned_data['email'],
                                        form.cleaned_data['password'])
        user.is_active = True
        # user.save()
        return super(UsuarioCreate, self).form_valid(form)

class UsuarioUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'email', 'password']
    success_url = reverse_lazy('licenciatarios:usuario')


class UsuarioDelete(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('licenciatarios:usuario')

class ConfigUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'email', 'password']
    success_url = reverse_lazy('licenciatarios:usuario')


class LoginView(View):
    success_url = reverse_lazy('licenciatarios:usuario')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        print('username')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect('/form')
            else:
                return HttpResponse("Inactive user.")
        else:
            return HttpResponseRedirect(settings.LOGIN_URL)

        return HttpResponseRedirect('/form')

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)

licencias/templates/licenciatarios/add-licenciatario.html
{% extends 'licenciatarios/base.html' %}
  {% block title %}
    {{ title }}
  {% endblock %}
    {% block content %}
    <div class="row">
      <div class="col-md-12">
        <div class="widget">
          <div class="widget-heading">
            <h3 class="widget-title">Agregar licenciatario</h3>
          </div>
          <div class="widget-body">

            <form class='form-horizontal' action="./new" method="post" target="_blank">

                {% csrf_token %}
                {% for field in form %}
                  <div class='form-group'>
                    <label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}</label>
                    <div class="col-sm-9 form-control-dad">
                      {{ field }}
                      <span id="txtEmailHor-error" class="help-block">{{field.errors}}</span>

                    </div>
                  </div>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

licencias/templates/licenciatarios/left-bar.html
{% load staticfiles %}
<!-- Main Sidebar start-->
<aside data-mcs-theme="minimal-dark" class="main-sidebar mCustomScrollbar">
  <div class="media user">
    <div class="media-left">
      <div id="esp-user-profile" data-percent="66" style="height: 56px; width: 56px; line-height: 40px; padding: 8px;" class="easy-pie-chart"><img src="{% static 'build/images/users/04.jpg' %}" alt="" class="avatar img-circle"></div>
    </div>
    <div style="overflow: visible" class="media-body media-middle">
      <h4 class="media-heading fs-16">{{ user.first_name }} {{user.last_name }}</h4>
      <div class="dropdown"><a id="dropdown-status" href="javascript:;" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" class="dropdown-toggle"><span class="status bg-success"></span> Opciones <span class="caret"></span></a>
        <ul aria-labelledby="dropdown-status" class="dropdown-menu animated fadeInUp">
          <li><a href="{% url 'licenciatarios:config'%}">Configuración</a></li>
          <li><a href="{% url 'licenciatarios:logout-view'%}"> Logout</a></li>
        </ul>
      </div>
    </div>
  </div>
  <ul class="list-unstyled navigation mb-0">
    <li class="sidebar-category">licenciatarios</li>
    <li class="panel"><a role="button" data-toggle="collapse" data-parent=".navigation" href="#collapse1" aria-expanded="false" aria-controls="collapse1" class="active collapsed"><i class="ion-ios-home-outline bg-danger"></i><span class="sidebar-title">Inicio</span></a>
      <ul id="collapse1" class="list-unstyled">
        <li><a href="{% url 'licenciatarios:licencia-nueva' %}" type="button" data-target=".bs-example-modal-form" data-toogle='modal' class="active">Agregar</a></li>
        <li><a href="#">Editar</a></li>
        <li><a href="#" class="active">Eliminar</a></li>
        <li><a href="#">Buscar</a></li>
      </ul>
    </li>
    <li class="panel"><a role="button" data-toggle="collapse" data-parent=".navigation" href="#collapse2" aria-expanded="false" aria-controls="collapse2" class="collapsed"><i class="ion-ios-printer-outline bg-danger"></i><span class="sidebar-title">Reportes</span></a>
      <ul id="collapse2" class="list-unstyled">
        <li><a href="#">Hoy</a></li>
        <li><a href="#">Noviembre</a></li>
        <li><a href="#">Personalizado</a></li>
      </ul>
    </li>
    <li class="sidebar-category">Sistema</li>
    <li class="panel"><a role="button" data-toggle="collapse" data-parent=".navigation" href="#collapse20" aria-expanded="false" aria-controls="collapse20" class="collapsed"><i class="ion-ios-folder-outline bg-black"></i><span class="sidebar-title">Usuarios</span></a>
      <ul id="collapse20" class="list-unstyled collapse">
        <li><a role="button" data-toggle="collapse" data-parent="#collapse20" href="#collapse201" aria-expanded="false" aria-controls="collapse201" class="collapsed">agregar</a>
        </li>
        <li><a role="button" data-toggle="collapse" data-parent="#collapse20" href="#collapse201" aria-expanded="false" aria-controls="collapse201" class="collapsed">buscar</a>
        </li>
      </ul>
    </li>
  </ul>


</aside>
<!-- Main Sidebar end-->

licencias/templates/licenciatarios/licenciatarios_confirm_delete.html
{% extends 'licenciatarios/base.html' %}
  {% block title %}
    {{ title }}
  {% endblock %}
    {% block content %}
    <div class="row">
      <div class="col-md-12">
        <div class="widget">
          <div class="widget-heading">
            <h3 class="widget-title">Estas seguro de eliminar {{licenciatarios.nombre}} </h3>
          </div>
          <div class="widget-body">

            
            <form action="" method="post">{% csrf_token %}
            <p>Estas seguro de eliminar la licencia "{{ object }}"?</p>
            <input type="submit" name="cancel" value="Cancelar" />
            <input type="submit" value="Si, deseo borrarla" />

            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

licencias/templates/licenciatarios/licenciatarios_form.html
{% extends 'licenciatarios/base.html' %}
  {% block title %}
    {{ title }}
  {% endblock %}
    {% block content %}
    <div class="row">
      <div class="col-md-12">
        <div class="widget">
          <div class="widget-heading">
            <h3 class="widget-title">Agregar licenciatario 222</h3>
          </div>
          <div class="widget-body">

            <form class='form-horizontal' method="post" >

                {% csrf_token %}
                {% for field in form %}
                  <div class='form-group'>
                    <label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}</label>
                    <div class="col-sm-9 form-control-dad">
                      {{ field }}
                      <span id="txtEmailHor-error" class="help-block">{{field.errors}}</span>

                    </div>
                  </div>
                {% endfor %}

                <input type="submit" value="Submit" />
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}